- name: variables to print
  hosts: web
  vars:
    COURSE: "Devops with AWS from PLAY level"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy"
  vars_prompt:
  - name: COURSE
    prompt: P1ease enter the course name
    private: false #not confidential
  tasks:
  - name: print the information
    vars:
      COURSE: "Devops with AWS from PLAY level"
      DURATION: "120HRS"
      TRAINER: "Sivakumar Reddy"
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{COURSE}}"
